In [1]:
import pandas as pd

/home/Chris/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/Chris/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

In [2]:
!ls

2006_crime_incidents.csv.gz  2015_crime_incidents.txt
2006_crime_incidents.txt     2016_crime_incidents.csv.gz
2007_crime_incidents.csv.gz  2016_crime_incidents.txt
2007_crime_incidents.txt     2017_crime_incidents.csv.gz
2008_crime_incidents.csv.gz  2017_crime_incidents.txt
2008_crime_incidents.txt     2018_crime_incidents.csv.gz
2009_crime_incidents.csv.gz  2018_crime_incidents.txt
2009_crime_incidents.txt     2019_crime_incidents.csv.gz
2010_crime_incidents.csv.gz  2019_crime_incidents.txt
2010_crime_incidents.txt     2020_crime_incidents.csv.gz
2011_crime_incidents.csv.gz  2020_crime_incidents.txt
2011_crime_incidents.txt     2021_crime_incidents.csv.gz
2012_crime_incidents.csv.gz  2021_crime_incidents.txt
2012_crime_incidents.txt     2022_crime_incidents.csv.gz
2013_crime_incidents.csv.gz  2022_crime_incidents.txt
2013_crime_incidents.txt     2023_crime_incidents.csv.gz
2014_crime_incidents.csv.gz  2023_crime_incidents.txt
2014_crime_incidents.txt     Untitled.ipynb
2015_crime_incidents.csv.gz  Untitled1.ipynb

In [4]:
df = pd.read_csv('2008_crime_incidents.txt')

In [7]:
df.sort_values('dispatch_date')

,objectid,dc_dist,psa,dispatch_date_time,dispatch_date,dispatch_time,hour,dc_key,location_block,ucr_general,text_general_code,point_x,point_y,lat,lng
63613,1075556,19,N,2008-01-01 04:53:00+00,2007-12-31,23:53:00,23.0,2.008190e+11,5200 BLOCK HARLAN ST,400,Aggravated Assault No Firearm,-75.226470,39.974798,39.974798,-75.226470
74578,1080287,2,M,2008-01-01 01:35:00+00,2007-12-31,20:35:00,20.0,2.007021e+11,6200 BLOCK HASBROOK AVE,600,Theft from Vehicle,-75.100408,40.050359,40.050359,-75.100408
86764,1665338,19,R,2008-01-01 02:17:00+00,2007-12-31,21:17:00,21.0,2.007191e+11,0 BLOCK N 54TH ST,2600,All Other Offenses,-75.228321,39.962043,39.962043,-75.228321
25546,745906,24,I,2008-01-01 01:30:00+00,2007-12-31,20:30:00,20.0,2.007241e+11,2700 BLOCK CASTOR AVE,600,Thefts,-75.091218,39.990890,39.990890,-75.091218
86884,1671334,25,L,2008-01-01 01:32:00+00,2007-12-31,20:32:00,20.0,2.007251e+11,4800 BLOCK MASCHER ST,1800,Narcotic / Drug Law Violations,-75.125763,40.023339,40.023339,-75.125763
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67916,1056564,22,N,2008-12-31 13:34:00+00,2008-12-31,08:34:00,8.0,2.008221e+11,2500 BLOCK N HOLLYWOOD ST,600,Theft from Vehicle,-75.179847,39.994041,39.994041,-75.179847
85627,1629523,14,N,2008-12-31 06:08:00+00,2008-12-31,01:08:00,1.0,2.008141e+11,6400 BLOCK CHEW AV,2600,All Other Offenses,-75.175807,40.052251,40.052251,-75.175807
28350,839837,24,P,2008-12-31 21:52:00+00,2008-12-31,16:52:00,16.0,2.008241e+11,300 BLOCK E ALLEGHENY AVE,600,Thefts,-75.123212,39.997762,39.997762,-75.123212
211673,14233053,39,H,2008-12-31 05:00:00+00,2008-12-31,00:00:00,19.0,2.008391e+11,3000 BLOCK N 25TH STREET,100,Homicide - Criminal,-75.171079,40.001992,40.001992,-75.171079
201536,2906536,23,J,2008-12-31 18:56:00+00,2008-12-31,13:56:00,13.0,2.008231e+11,2400 BLOCK N COLLEGE AVE,1100,Fraud,-75.177125,39.974336,39.974336,-75.177125